In [1]:
import numpy as np

In [9]:
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9, 8, 7], [6, 5, 4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [6]:
# Get Dimension
a.ndim

1

In [7]:
# Get Shape
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int16')

In [12]:
# Get Size in bytes
a.itemsize

2

In [15]:
# Get Total Size
a.size # Size of the array in  value
a.nbytes # Size of the array in bytes

6

In [16]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# Get a specific element
a[1, 5] # Using positive index
a[1, -2] # Using neg index

13

In [21]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [25]:
# Get a little fancy
a[0, 1:-1:2]

array([2, 4, 6])

In [26]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [28]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
# 3d example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific element
b[0, 1, 1]

4

In [37]:
b[:, 0, :]

array([[1, 2],
       [5, 6]])

### Initializing diff types of array

In [43]:
# All 0s matrix
np.zeros(5)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [46]:
# any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [49]:
# Any other number (full-like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
# Random decimal numbers
np.random.rand(4, 2, 3)

array([[[0.645063  , 0.1415213 , 0.31606102],
        [0.33314189, 0.85017911, 0.46586389]],

       [[0.08096652, 0.90160315, 0.19387148],
        [0.70331417, 0.40756742, 0.24035526]],

       [[0.22406561, 0.56104365, 0.43907293],
        [0.62490132, 0.83679137, 0.8326228 ]],

       [[0.36752104, 0.09370939, 0.26358835],
        [0.09040056, 0.26477705, 0.91082509]]])

In [52]:
np.random.random_sample(a.shape)

array([[0.25059489, 0.94061987, 0.82942047, 0.36107737, 0.03742126,
        0.16289912, 0.48188781],
       [0.69455837, 0.32352914, 0.85207364, 0.00328733, 0.25311114,
        0.40290372, 0.59797613]])

In [59]:
# Random integer values
np.random.randint(10,20, size=(3,3)) # (starting_value, ending_value, size=())

array([[15, 18, 15],
       [15, 12, 14],
       [13, 15, 12]])

In [60]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
#Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3,3))
z[1, 1]=9

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### be careful when copying arrays

In [71]:
a = np.array([1,2, 3])
a

array([1, 2, 3])

In [72]:
b = a
b

array([1, 2, 3])

In [74]:
b[0] = 100
b

array([100,   2,   3])

In [75]:
a

array([100,   2,   3])

In [77]:
b = a.copy()
b

array([100,   2,   3])

#### Mathematics

In [78]:
a = np.array([1, 2, 3, 4])

In [79]:
a+2

array([3, 4, 5, 6])

In [80]:
a - 2

array([-1,  0,  1,  2])

In [81]:
a*2

array([2, 4, 6, 8])

In [82]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [83]:
b = np.array([1, 0, 1, 0])

In [84]:
a+b

array([2, 2, 4, 4])

In [85]:
a**2

array([ 1,  4,  9, 16])

In [91]:
# Take the sin
np.cos(a)

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

In [92]:
# More Maths
# https://numpy.org/doc/stable/reference/routines.math.html

#### Linear Algebra

In [90]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [93]:
# Linear Algebra
# https://numpy.org/doc/stable/reference/routines.linalg.html

#### Statistics

In [95]:
stats = np.array([[1, 2, 3],
                 [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
np.min(stats, axis = 1)

array([1, 4])

In [100]:
np.max(stats, axis = 1)

array([3, 6])

In [101]:
np.sum(stats, axis=0)

array([5, 7, 9])

#### Reorganizing arrays

In [107]:
before = np.array([[1, 2, 3, 4], [5,6, 7,8]])
print(before)

after = before.reshape((2, 2, 2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [111]:
# Vertically stacking
v1 = np.array([1,2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [112]:
# Horizontal stacking
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [113]:
# Column stacking